[build-system]
requires = [
    "setuptools>=30.3.0",
    "wheel",
]

[tool.black]
line-length = 79
target-version = ['py36']
skip-string-normalization = false

[tool.isort]
skip = [".gitignore"]
extend_skip = [".rst",".*"]
skip_glob=["docs/*","venv/*",".tox/*"]
extend_skip_glob=[".*/*"]